server.port=8082
spring.datasource.url=jdbc:postgresql://db.mljayfwokmbahzahsgsu.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=C0legio!2026_DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
