# Puerto en el que se levantará el BFF
server.port=8081

# Nombre de la aplicación (útil para logs y monitoreo)
spring.application.name=bff

# URL del microservicio Académico (cambia según entorno)
academico.url=http://localhost:8082
