server.port=8084

spring.datasource.url=jdbc:postgresql://dpg-d8m17h28qa3s73av8g9g-a.oregon-postgres.render.com:5432/colegio_db_glgw?sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=colegio_db_glgw_user
spring.datasource.password=7y5cCLqL1cS7CjWj9XuOYI7XARUwEdPg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.application.name=comunicaciones
