server.port=8083

spring.datasource.url=jdbc:postgresql://dpg-d7v50avavr4c739gk82g-a.oregon-postgres.render.com:5432/colegio_db_a7sc
spring.datasource.username=colegio_db_a7sc_user
spring.datasource.password=UIPUnStTmwZVOQVQQI9z5Csj8iJQZF99
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.application.name=asistencia

